#!/bin/sh
set -e

#DEBHELPER#

case "$1" in
  purge)
    rm -rf /var/lib/rmilter
    exit 0;;
  remove|upgrade|disappear|failed-upgrade|abort-*)
    exit 0;;
  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1;;
esac
