#!/bin/sh
set -e

case "$1" in
    configure)
       adduser --quiet \
               --system \
               --group \
               --home /run/rmilter \
               --no-create-home \
               --disabled-login \
               --gecos "rmilter" \
               --force-badname \
               _rmilter
    ;;

    abort-*)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
