#!/bin/sh
set -e

case "$1" in
    configure)
       adduser --quiet \
               --system \
               --group \
               --home /run/rmilter \
               --no-create-home \
               --disabled-login \
               --gecos "rmilter" \
               --force-badname \
               _rmilter
    ;;

    abort-*)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

if [ -x /etc/init.d/rmilter ]; then
    update-rc.d rmilter defaults >/dev/null
    if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
    else
        invoke-rc.d rmilter start || exit $?
    fi
fi

#DEBHELPER#

exit 0
