Document: rmilter
Title: Debian rmilter Manual
Author: <insert document author here>
Abstract: This manual describes what rmilter is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rmilter/rmilter.sgml.gz

Format: postscript
Files: /usr/share/doc/rmilter/rmilter.ps.gz

Format: text
Files: /usr/share/doc/rmilter/rmilter.text.gz

Format: HTML
Index: /usr/share/doc/rmilter/html/index.html
Files: /usr/share/doc/rmilter/html/*.html
