#!/bin/sh
# PROVIDE: rmilter
# REQUIRE: LOGIN
# BEFORE: postfix
# KEYWORD: shutdown

#
# Add the following line to /etc/rc.conf to enable countd:
# rmilter (bool):          Set to "NO" by default.
#                          Set it to "YES" to enable rmilter.

. /etc/rc.subr

name="rmilter"
rcvar=rmilter_enable
command="/usr/local/sbin/rmilter"

load_rc_config $name

: ${rmilter_enable="NO"}
: ${rmilter_pidfile="/var/run/rmilter/rmilter.pid"}
: ${rmilter_socket="/var/run/rmilter/rmilter.sock"}
: ${rmilter_user="postfix"}

stop_postcmd="rm -f $rmilter_pidfile ; if [ -n $rmilter_socket ] && [ -S $rmilter_socket ] ; then rm -f $rmilter_socket ; fi"
start_precmd="if [ -n $rmilter_socket ] && [ -S $rmilter_socket ] ; then rm -f $rmilter_socket ; fi"

extra_commands="reload"
sig_reload="USR1"

command_args="$procname -c /usr/local/etc/rmilter.conf"

run_rc_command "$1"
