#!/bin/sh
# PROVIDE: rmilter
# REQUIRE: LOGIN
# BEFORE: mail
# KEYWORD: shutdown
#
# Add the following line to /etc/rc.conf to enable rmilter:
# rmilter_enable="YES"
#

. /etc/rc.subr

name="rmilter"
rcvar=rmilter_enable
command="%%PREFIX%%/sbin/rmilter"

load_rc_config $name

: ${rmilter_enable="NO"}
: ${rmilter_pidfile="/var/run/rmilter/rmilter.pid"}
: ${rmilter_socket="/var/run/rmilter/rmilter.sock"}
: ${rmilter_user="_rmilter"}
: ${rmilter_group="mail"}

rmilter_cleanup() {
	rm -f $rmilter_pidfile || true
	if [ -n $rmilter_socket ] && [ -S $rmilter_socket ] ; then
		rm -f $rmilter_socket || true
	fi
}

rmilter_fixupbloodylibmilter() {
	if [ -n $rmilter_socket ] && [ -S $rmilter_socket ] ; then
	 	chown ${rmilter_user}:${rmilter_group} $rmilter_socket
		chmod 774 $rmilter_socket
	fi
}

start_precmd=rmilter_cleanup
start_postcmd=rmilter_fixupbloodylibmilter
stop_postcmd=rmilter_cleanup

extra_commands="reload"
sig_reload="USR1"

command_args="$procname -c %%PREFIX%%/etc/rmilter.conf"

run_rc_command "$1"
